db:
  name: user_management
  user: postgres
  password: 1q2w3e

spring:
  application:
    name: student-management

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${db.user}
    password: ${db.password}
    url: jdbc:postgresql://localhost:5432/${db.name}

  mvc:
    hidden-method:
      filter:
        enabled: true

server:
  port: 4000
  servlet:
    context-path: /user-management

security:
  enabled: true
